# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 01:53
from __future__ import unicode_literals

from django.db import migrations, models
import dju_common.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('dju_privateurl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateurl',
            name='data',
            field=dju_common.fields.json.JSONField(blank=True, default=None, dump_kwargs={b'cls': dju_common.fields.json.JSONEncoder, b'separators': (b',', b':'), b'use_decimal': True}, load_kwargs={b'use_decimal': True}, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='privateurl',
            name='token',
            field=models.SlugField(max_length=65, verbose_name='token'),
        ),
    ]
